[package]
name = "rust_druid_epub_reader"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies]
druid = { git = "https://github.com/linebender/druid.git", features=["im", "svg", "image", "png", "jpeg"] }
open = "1.6"
xmlparser = "0.13.3"
tracing = "0.1.36"
epub = "1.2.3"
# leptess = "0.11.0" 
